# Generated by Django 2.2 on 2020-05-31 00:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='date_ended',
        ),
        migrations.AddField(
            model_name='buy',
            name='category',
            field=models.CharField(default='Fountain Pens', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='date_ends',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='description',
            field=models.TextField(default='This is a cool description for an item.', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buy',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='product_pics'),
        ),
        migrations.AddField(
            model_name='buy',
            name='name',
            field=models.CharField(default='A real cool Fountain Pen', max_length=300),
            preserve_default=False,
        ),
    ]
